import type { Metadata } from "next";
import "./globals.css";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = (await headers()).get("x-pathname") ?? "";
  const locale = pathname.split("/")[1] || "en";
  return (
    <html id="hidden" className="h-screen w-screen bg-gray-400" lang={locale}>
      <body className="w-full h-full">{children}</body>
    </html>
  );
}
